# Generated by Django 6.0.3 on 2026-05-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_property_property_type_tourbooking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourbooking",
            name="agent_message",
            field=models.TextField(
                blank=True,
                help_text="Message from agent regarding status update",
                null=True,
            ),
        ),
    ]
