# Generated by Django 6.0.3 on 2026-06-28 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_tourbooking_agent_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Image"
            ),
        ),
    ]
